### ISSUE TITLE
1.4.0 Release task list

### ISSUE THREAD

**Issue by craigh** [zikula/core#1540]
# Overview
This is not a bug report or a place to mention new issues. Please report all issues as usual.

The intention of this ticket is to identify all the items that must be done as we approach and finalize an actual release of 1.4.0. This has been an extended release cycle (since 1.3.5) and we must begin to wrap this up and get something out the door. I know we don't want to identify a release date, but a task list is certainly appropriate, I think.

# Core Issues
 - [x] Finish Symfony Routing (#1519, #1552) assigned: @cmfcmf 
 - [x] Finish User Module review (#900) assigned: @cmfcmf 
 - [x] Finish conversion to Bootstrap styling (css specifically) assigned: @phaidon 
 - [ ] Finish conversion to jQuery/Bootstrap javascript ( #1214, ~~#1752, #1757~~, #1758, ~~#1759~~) assigned: @phaidon 
 - [x] ~~Conversion of all system modules and themes to psr-4 (refs #1614)~~
 - [x] Finalize 2.0.0-compatible module/theme structure. assigned: @drak
 - [x] Resolve mobile theme problems (#1336, #1046)
 - [x] ~~Resolve issue with inactive modules and event listeners (#523)~~
 - [x] Remove PersistentModuleHandlers (#1545) assigned: @craigh
 - [x] correct psr-4 dependency injection issues (#1570)

# Value Add-On modules
## Profile
 - [x] Conversion to Bootstrap css
 - [ ] Conversion to jQuery/Bootstrap js
 - [x] ~~Conversion to psr-4~~

## Legal
 - [x] Conversion to Bootstrap css
 - [x] Conversion to jQuery/Bootstrap js
 - [x] Conversion to psr-4
 - [ ] Outstanding issues  (https://github.com/zikula-modules/Legal/issues?state=open)

# Documentation
 - [x] Document user upgrade process carefully (#554)
 - [ ] Document developer module/theme requirements for new version (https://github.com/zikula/core/blob/1.4/src/docs/en/dev/UPGRADE-1.4.0.md)
 - [ ] Document Forward Compatibility Layer for modules/themes (^^^)
 - [x] Document new events #1551

# Build
 - [ ] QA release cycle and voting

# Community Website
 - [ ] Ugrade on release

# Other
??

# Final
Those with access should feel free to modify this ticket as required. If removing something, please use ~~strikethrough text~~ instead of deleting. Those without access can comment below and adjustments can be made in the ticket.

**Comment by craigh** [comment]
closing this issue as it is now actually making it harder to track what needs to be done, IMO. If you disagree @Guite then please reopen and delete this comment :wink:
