### ISSUE TITLE
Routing task list

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#1552]
# Ready to be implemented
- [x] Implement http://symfony.com/doc/current/cookbook/routing/redirect_trailing_slash.html
- [x] Maybe add a new symfony route smarty plugin @craigh 
- [x] Add final documentation on routing. Useful resources:
  - https://github.com/zikula/core/pull/1518/files
  - https://github.com/zikula/core/pull/1519
# To be discussed
- [x] Think about themes  
  > Use case one: See a news list in RSS is done by adding &theme=rss. This is easily replacable by using /my/cool/route.rss instead.
  -- @cmfcmf
  > This is how Symfony handles those cases: http://symfony.com/doc/current/book/templating.html#template-formats - we know the &theme= thing for these cases is a terrible hack and actually unworkable in most cases where the controller doesnt actually return that format.
  -- @drak
  > another use case: theme=printer
  -- @craigh 

Themes will work as before and if needed be activated by adding the theme parameter just as before.
