### ISSUE TITLE
Convert directory structure and configuration to Sf5 default

### ISSUE THREAD

**Issue by Guite** [zikula/core#4052]
The following tasks would be relevant for getting closer some best practices, like [standard directory layout](https://symfony.com/doc/current/best_practices.html#use-the-default-directory-structure) and using/supporting [environment variables](https://symfony.com/doc/current/best_practices.html#use-environment-variables-for-infrastructure-configuration).

- [x] 1. Rename/move config directory and files (done in #4079, see changes [here](https://github.com/zikula/core/pull/4079/files#diff-8ee894204f471eae7d606c828a1af52f))
- [x] 2. Rename/move other directories and files (done in #4079, see changes [here](https://github.com/zikula/core/pull/4079/files#diff-8ee894204f471eae7d606c828a1af52f))
- [x] 3. Further changes to directory layout (done in #4084, see changes [here](https://github.com/zikula/core/pull/4084/files#diff-8ee894204f471eae7d606c828a1af52f))
- [x] 4. Post processings (done in #4087)

**Comment by craigh** [comment]
perhaps we could slack on Saturday and discuss?

**Comment by Guite** [comment]
Yes. If you have two minutes later, I'd like to coordindate something else with you briefly though.

**Comment by craigh** [comment]
about 3pm EST

**Comment by craigh** [comment]
While [this page](https://symfony.com/doc/current/bundles.html) discourages bundles at all, like it or not, Zikula _will_ be a collection of bundles. I think we can eventually put CoreBundle, CoreInstallerBundle, FormExtensionBundle, HookBundle and WorkflowBundle into vendors as a composer requirement. Now that I [moved ](401c464) bootstrap.php, this leaves only RequirementChecker in `/lib`. For the moment, I propose this:

    src/
        Zikula/
            CoreBundle/
            CoreInstallerBundle/
            FormExtensionBundle/
            HookBundle/
            WorkflowBundle/
            RequirementChecker.php
            Kernel.php

this eliminates the `/lib` and also `/Bundles` sub directories in that path and aligns with Sy5 best-practices

In the distribution, the Bundles would move to `/vendor` leaving only RequirementChecker.php & Kernel.php

I think this can all be done immediately and continue with a working install.

**Comment by Guite** [comment]
> While this page discourages bundles at all, like it or not

Initially I misunderstood this, too. When Symfony 4 arrived I asked about it in the Symfony Slack. The answer was that bundles are still fine for reusable components which are distributed.
Bundles are only discouraged for "own application code" (that is what the linked page says), which refers to the former AppBundle.

**Comment by craigh** [comment]
just realized I misspoke above. I meant

    src/
        RequirementChecker.php
        Kernel.php
        Zikula/
            CoreBundle/
            CoreInstallerBundle/
            FormExtensionBundle/
            HookBundle/
            WorkflowBundle/

but you didn't say what you thought about the structure

**Comment by Guite** [comment]
I am fine with it.

**Comment by craigh** [comment]
> composer.json would need to be altered to change the auto-loading

there needs to be an upgrade to the bundles table also for this

**Comment by Guite** [comment]
> there needs to be an upgrade to the bundles table also for this

no.

**Comment by craigh** [comment]
>  public: the next steps outlined below include renaming web/ to public/ and moving index.php to public/index.php; actually, what we currently have under web/ should then go into assets/, right?

you were right the first time. web -> public. In Sy5 if you require a symfony bundle with assets and run `assets:install`, they are installed in `public/bundle/<bundlename>/css|js|images/`

> Not sure about overriding asset files though: earlier we had the possibility copy a js file, a css file or even an image into app/Resources/.../ and could customise it.

This should be possible, we just would need to create a location in public, e.g. `public/overrides/<bundlename>/css|js|images/`

>  src: actually we should move Kernel.php, RequirementChecker.php, modules/, system/, themes/ and Zikula/ into src/. 

Kernel and RequirementChecker already have been moved. For now I think we keep modules|system|themes & Zikula in `src`

> It's just strange, because in our repository we have everything under src/ ... maybe it's time to get rid of this and move everything one level up

Yes, I think so. most (except noted above) will move up, imo

>  Decide about how to treat modules, system, themes in future. Temporarily we could collect them e.g. in a common parent folder like e.g. extensions?

modules and themes will end up as `extensions/` for sure. I'm still not sure about system. I think one possibility is `vendor/`

---

The other thing to remember here is that we are moving to a new structure where the dev environment that we work in will actually be different than the distribution and actual _usage_ of the product. The best example of this is that all the Core bundles will move from Zikula to `vendor/` in the distribution. There will be other differences of course also.

**Comment by craigh** [comment]
I think this is a good starting point for discussion:

```xml
    zikula/
    ├─ bin/
    │  └─ console
    ├─ config/
    │  ├─ packages/
    │  └─ services.yaml
    ├─ extensions/<perhaps in src/extensions?>
    │  ├─ zikula/
    │  |  ├─ ProfileModule
    │  |  ├─ OAuthModule
    │  |  └─ BootstrapTheme
    │  └─ acme/
    └─ public/
    │  ├─ build/
    │  ├─ bundles/<bundlename>/css|js|images
    │  ├─ extensions/<extensionname>/css|js|images
    │  ├─ overrides/<extensionname>/css|js|images
    │  └─ index.php
    ├─ src/
    │  ├─ Kernel.php
    │  └─ Zikula/
    │     ├─ CoreBundle
    │     ├─ CoreInstallerBundle
    │     ├─ FormExtensionBundle
    │     ├─ HookBundle
    │     └─ WorkflowBundle
    ├─ templates/
    ├─ tests/
    ├─ translations/
    ├─ var/
    │  ├─ cache/
    │  └─ log/
    └─ vendor/
       └─ zikula
           ├─ CoreBundle
           ├─ CoreInstallerBundle
           ├─ FormExtensionBundle
           ├─ WorkflowBundle
           ├─ AdminModule
           ├─ BlocksModule
           ├─ CategoriesModule
           ├─ ...
           └─ ZAuthModule
```

**Comment by Guite** [comment]
Notes from the last arrangement in Slack:

- updated directory layout from above is fine
- consequences of moving everything except sources one level up
  - main repo of https://github.com/symfony/requirements-checker/ can be used again
  - `FixAutoloaderCommand` can be removed because `composer.*` and `vendor` folder will be on the same level again
- `public/index.php` resources: [this](https://medium.com/@runawaycoin/deploying-symfony-4-application-to-shared-hosting-with-just-ftp-access-e65d2c5e0e3d), [this](https://symfony.com/doc/current/setup/web_server_configuration.html), [this](https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/public/.htaccess)

**Comment by craigh** [comment]
corrected:

```
    ├─ src/
    │  |  ├─ extensions/ (for the moment: modules|theme and system in dev)
    │  |  |  ├─ zikula/
    │  |  |  |  ├─ ProfileModule
    │  |  |  |  ├─ OAuthModule
    │  |  |  |  └─ BootstrapTheme
    │  |  |  └─ acme/
    │  |  |     └─ CustomTheme
```

to 
```
    ├─ src/
    |  ├─ extensions/ (for the moment: modules|theme and system in dev)
    |  |  ├─ zikula/
    |  |  |  ├─ ProfileModule
    |  |  |  ├─ OAuthModule
    |  |  |  └─ BootstrapTheme
    |  |  └─ acme/
    |  |     └─ CustomTheme
```

because former implied additional (invisible) directory layer

**Comment by craigh** [comment]
for step 4, please do each subtask as new PR

**Comment by Guite** [comment]
Moved tasks wrt environment variables to own issue #4093

Closing.
