### ISSUE TITLE
Review the whole user registration / login process

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#900]
- [x] https://github.com/craigh/Captcha/issues/8, #1018, #301 
- [x] [**#1568**] **Problem with new account registration - missing icons when 3rd party auth modules are used**
- [x] [**#1568**] Fix layout ![bildschirmfoto vom 2014-01-02 11 55 33](https://f.cloud.github.com/assets/2145092/1831798/741de886-739c-11e3-9d4e-09cdbc51c675.png)
- [x] [**#1568**] The returnURL gets lost sometimes.
- [x] [**#1568**] Fix CSS / JS problem when login block and login form are displayed on the same page
- [x] [ **#908** ] Remove password reminder requirement if a third party auth-module is used. <= Major bug, no third-party auth module will work, because there normally is no password so a password reminder is useless.
- [x] [ **#992** ] Change E-Mail text saying "You can now register using your password…" when an third-party auth-module is used: The user might have no password.
- [x] [ **#908** ] Introduce a modvar for controlling the password reminder.
- [x] [ **#997** ] Review pass reminder in force password change
- [x] [ **Is working** ] Review 'Lost password' for external auth modules.
- [x] [ **#997** ] Review pass meter
- [x] [ **#997** ] Review 'Force password change', 'Reverify password', etc. for third party auth modules.
- [x] [ **#997** ] Add #488.
